services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - athlete-insight-network

  python-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: python-app
    env_file: .env
    volumes:
      - ../:/app
      - /app/__pycache__
      - ../../activity_fetcher/data:/data
    working_dir: /app
    environment:
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - OLLAMA_HOST=192.168.1.70  # Windows host IP for Podman
      - OLLAMA_PORT=11434
    networks:
      - athlete-insight-network
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true

volumes:
  chroma_data:
    driver: local

networks:
  athlete-insight-network:
    driver: bridge